require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

$FirebaseSDKVersion = '8.13.0'
$RNFirebaseAsStaticFramework = true

platform :ios, '11.0'

target 'Wearables' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )


  pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'
  pod 'RNPDF', :path => '../node_modules/react-native-view-pdf'
  permissions_path = '../node_modules/react-native-permissions/ios'
    pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways/Permission-LocationAlways.podspec"
    pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse/Permission-LocationWhenInUse.podspec"
    

    pod 'SDWebImage', '5.12.6', :modular_headers => true
   pod 'DKImagePickerController', '4.1.7'
   pod 'DateToolsSwift'
   pod 'ZDCChat/API'
   
  

  pod 'react-native-image-sequence', :path => '../node_modules/react-native-image-sequence'

  target 'WearablesTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  #post_install do |installer|
   # react_native_post_install(installer)
    #__apply_Xcode_12_5_M1_post_install_workaround(installer)
  #end
  
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

     installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
     end
    end
end
